version: '3.8'

services:
  bot:
    build: .
    environment:
      - TOKEN=${TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/botdb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=botdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: